### PR TITLE
Network listener changes

### PR DESCRIPTION
**Pull request by trea**
Hi folks, I hope contribution is welcome. I have been tinkering around with this module. Feel free to accept as-is or remix at will. I'd also be happy to address any feedback or questions.

### CODE REVIEW

**Comment by mholt** [comment]
Thanks, this is definitely interesting. So you've made this into a reverse proxy transport -- can you elaborate on your changes a bit so we know what to expect during a review?

**Comment by mholt** [comment]
(Sorry, was delayed by some things last week.)

That's very cool! I think overall these changes are good, and I will try to do a more formal review soon. I'd love for a member of the TS team to review this if it's something they're willing to accept! (@Xe ? @willnorris ?)

**Comment by trea** [comment]
No worries, thanks!

**Comment by willnorris** [comment]
Yeah, these changes look great, and I'm excited to try them out (hopefully tomorrow?).  The approach looks good, and I suspect most of my comments will just end up being stylistic (looks like the second commit needs goimports?), and some additional documentation.  We also need to think about how you juggle the auth keys if you have multiple of these, or mixed with listeners.  I think all this predates OAuth support for Tailscale as well, so there's probably more work to do there anyway independent of this change.

**Comment by icb-** [comment]
Caddy introduced [a breaking change](https://github.com/caddyserver/caddy/commit/e16a886814d8cd43d545de38a4d6b98313fb31cb) so `caddytls.AutomationPolicy` field `Subjects` needs to be `SubjectsRaw` at [`command.go` line 202](https://github.com/trea/caddy-tailscale/blob/network-listener-changes/command.go#L202) to build against Caddy `master`. After fixing that, you should be able to build with `xcaddy build master --with github.com/tailscale/caddy-tailscale=github.com/trea/caddy-tailscale@network-listener-changes`.

**Comment by mholt** [comment]
Ah, yeah -- that's actually an API surface that I think is referenced only by this project outside our official Caddy repo. (The typical API surface is the JSON field name.) Generally, external code doesn't access that but I guess this is a special case I didn't realize. (Sorry!) But yeah that should be an easy fix :sweat_smile:

**Comment by willnorris** [comment]
tested and this works great... this is really cool!  Thanks for the contribution, and for the patience in me getting around to reviewing it! :)  I've got a few minor formatting changes I'll push to your fork and then merge.

**Comment by trea** [comment]
Oh no worries, I'm glad it all worked out and stoked I was able to contribute! Until next time! 🎉

**Pull request merged**
